### ISSUE TITLE
Share an idea for the project

### ISSUE THREAD

**Issue by enma1009** [omiinaya/Project1#2]
Share an idea for a potential App that we can create for the project.

**Acceptance criteria**
- [ ] Must be something that we can do
- [ ] Must be something that meets the project requirements
- [ ] Must be something doable in 2 weeks
- [ ] Must have real use and utility

**Comment by omiinaya** [comment]
-replace dracula default with NY Times top sellers info.
-add share buttons for social media and SMS.
-add audiobooks section for the books that support it.
-add previous button or expand results page to display more than one result (?)

**Comment by omiinaya** [comment]
no more ideas.
